debugging

diff --git a/.github/workflows/workflow-check-file-presence.yml b/.github/workflows/workflow-check-file-presence.yml
--- a/.github/workflows/workflow-check-file-presence.yml
+++ b/.github/workflows/workflow-check-file-presence.yml
@@ -10,24 +10,19 @@ on:
 jobs:
   check-files:
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        file: ${{fromJson(github.event.inputs.files)}}
     steps:
     - name: Check out code
       uses: actions/checkout@v3
-      
-    - name: Echo Input
-      run: |
-        echo "Files: ${{ github.event.inputs.files }}"
-      shell: bash
 
     - name: Check for file
       run: |
-        if [[ -f "${{ matrix.file }}" ]]; then
-          echo "${{ matrix.file }} exists."
-        else
-          echo "Error: ${{ matrix.file }} does not exist!" >&2
-          exit 1
-        fi
+        IFS=',' read -ra FILE_ARRAY <<< "${{ github.event.inputs.files }}"
+        for file in "${FILE_ARRAY[@]}"; do
+          if [[ -f "$file" ]]; then
+            echo "$file exists."
+          else
+            echo "Error: $file does not exist!" >&2
+            exit 1
+          fi
+        done
       shell: bash
