issue #172: fix

diff --git a/.github/workflows/workflow-detect-secret-leaks.yml b/.github/workflows/workflow-detect-secret-leaks.yml
--- a/.github/workflows/workflow-detect-secret-leaks.yml
+++ b/.github/workflows/workflow-detect-secret-leaks.yml
@@ -48,7 +48,7 @@ jobs:
           for var in $(compgen -e VAULTACTIONKEY_); do
             value="${!var}"
             if [ -n "$value" ]; then
-              git secrets --add --literal -- "$value" || echo "git secrets failed for variable $var" >&2
+              git secrets --add --literal "$value" || echo "git secrets failed for variable $var" >&2
             else
               echo "Skipping empty variable $var"
             fi
